### ISSUE TITLE
[FR]能否隐藏掉sidenote的callout标题？

### ISSUE THREAD

**Issue by Flyingfolder** [xhuajin/obsidian-sidenote-callout#10]
编注寸土寸金，希望能增加新的callout语法，能够隐藏掉sidenote的标题。

比如
```
> [!note|aside-l-noheadings]

> [!note|aside-l-noh]

```

**Comment by GreyElaina** [comment]
```css

/* 隐藏标题核心逻辑 */
.callout[data-callout-metadata*="-noheadings"] .callout-title,
.callout[data-callout-metadata*="-noh"] .callout-title {
  display: none !important;
}

/* 完全重置网格布局 */
.callout[data-callout-metadata*="-noheadings"],
.callout[data-callout-metadata*="-noh"] {
  grid-template-columns: 1fr !important;
  /* 单列布局 */
  grid-template-areas: "content";
  /* 明确布局区域 */
  --speaker-block-width: 0 !important;
  /* 消除标题区域影响 */
}

/* 调整内容区域定位 */
.callout[data-callout-metadata*="-noheadings"] .callout-content,
.callout[data-callout-metadata*="-noh"] .callout-content {
  grid-area: content;
  /* 指定网格区域 */
  padding: 0 var(--block-spacing) !important;
  width: 100% !important;
}

/* 修复顶部标题模式下的布局冲突 */
.top-sidenote-callout-title .callout[data-callout-metadata*="-noheadings"],
.top-sidenote-callout-title .callout[data-callout-metadata*="-noh"] {
  grid-template-columns: 1fr !important;
}

/* 确保折叠图标彻底隐藏 */
.callout[data-callout-metadata*="-noheadings"] .callout-fold,
.callout[data-callout-metadata*="-noh"] .callout-fold {
  display: none !important;
}
```

Completed by deepseek-r1
