### ISSUE TITLE
突然就失效了，打开 sidenote-callout css片段后 在阅读模式内什么都不显示了

### ISSUE THREAD

**Issue by ACedison** [xhuajin/obsidian-sidenote-callout#8]
不知道是否和版本有关系  目前我 obsidian 是 v1.7.4

**Comment by philonaut666** [comment]
我也是，同样的问题

**Comment by xhuajin** [comment]
可能是和使用的css或者主题冲突了，因为我目前用1.8.4版本的obsidian测试，在阅读模式下能够正常显示

**Comment by shniubobo** [comment]
在css文件里添加这一段可以解决：

```css
.markdown-reading-view .callout[data-callout-metadata*="aside-l"] {
  left: calc(100% - var(--aside-width) - (50% + var(--file-line-width)/2 + var(--aside-offset)));
  right: calc(50% + var(--file-line-width)/2 + var(--aside-offset));
}

.markdown-reading-view .callout[data-callout-metadata*="aside-r"] {
  left: calc(50% + var(--file-line-width)/2 + var(--aside-offset));
  right: calc(100% - var(--aside-width) - (50% + var(--file-line-width)/2 + var(--aside-offset)));
}
```
